### ISSUE TITLE
Always place from elements in a ... form 😀

### ISSUE THREAD

**Issue by joostf** [Siem-P/fix-the-flow-interactive-website#2]
https://github.com/Siem-P/fix-the-flow-interactive-website/blob/d8711de58afbe73fe6e8642eb51c23cf48a92abf/index.html#L38

**Comment by Siem-P** [comment]
`<input>` staat nu tussen `<form>` tags.

<img width="420" alt="Screenshot 2022-12-16 at 13 14 18" src="https://user-images.githubusercontent.com/64197688/208095936-15e2b79d-57ff-4185-b163-72a631bb25f8.png">
