### ISSUE TITLE
Try to use more concise and meaningful names 

### ISSUE THREAD

**Issue by joostf** [Siem-P/fix-the-flow-interactive-website#3]
https://github.com/Siem-P/fix-the-flow-interactive-website/blob/d8711de58afbe73fe6e8642eb51c23cf48a92abf/styles/style.css#L4-L8

**Comment by Siem-P** [comment]
Zijn dit duidelijke benamingen?

<img width="511" alt="Screenshot 2022-12-16 at 13 01 28" src="https://user-images.githubusercontent.com/64197688/208094057-a4d3d741-9dd8-4568-b7a9-1cfedc89e9d6.png">
